---

- name: Install Minikube
  ansible.builtin.get_url:
    url: "https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64"
    dest: "/usr/local/bin/minikube"
    mode: 0755

- name: Accept virtualbox-ext-pack select license
  ansible.builtin.debconf:
    name: virtualbox-ext-pack
    question: virtualbox-ext-pack/license
    value: 'true'
    vtype: select

- name: Install packages virtualbox
  ansible.builtin.apt:
    name: "{{ packages }}"
  vars:
    packages:
      - virtualbox
      - virtualbox-ext-pack
    update_cache: true

- name: Install Kubectl
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/v1.27.0/bin/linux/amd64/kubectl"
    dest: "/usr/local/bin/kubectl"
    mode: 0755      

- name: Minikube start
  become_user: admin
  ansible.builtin.shell: minikube start --nodes 5
  register: __minikube_start
  
- name: Debug minikube start
  ansible.builtin.debug:
    msg: "{{ __minikube_start.stdout_lines }}"

- name: Debug Minikube status
  become_user: admin
  ansible.builtin.shell: minikube node list
  register: __minikube_list

- name: Debug Kubectl
  ansible.builtin.shell: kubectl version --client
  register: __kubectl_version

- name: Print Debug
  ansible.builtin.debug: 
    msg: "{{ item }}"
  loop:
    - "{{ __kubectl_version.stdout_lines }}"
    - "{{ __minikube_list.stdout_lines  }}"